spring:
  application:
    name: reactive.spring.boot
    version:  ${APP_VERSION:1.0.0}

server:
  port: ${service.port:8001}
  servlet:
    context-path: ${contextPath:}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info
